# Generated by Django 4.2.8 on 2024-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido_por_peso',
            field=models.BooleanField(default=False),
        ),
    ]
