# Generated by Django 4.2.8 on 2024-01-22 13:45

from django.db import migrations, models
import django.db.models.deletion
import pdvweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(default=pdvweb.models.default_nome, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='operador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdvweb.operador'),
        ),
    ]
