# Generated by Django 4.2.8 on 2024-01-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
