# Generated by Django 4.2.8 on 2024-01-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='operador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdvweb.operador'),
        ),
    ]
