# Generated by Django 5.0.1 on 2024-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0002_alter_itemvenda_quantidade_alter_itemvenda_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
