# Generated by Django 4.2.8 on 2024-02-02 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0002_produto_vendido_por_peso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='produtos',
            new_name='itens_venda',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='vendido_por_peso',
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda_rel', to='pdvweb.produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda_rel', to='pdvweb.venda'),
        ),
        migrations.CreateModel(
            name='ProdutoPorPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_por_kilo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque_em_kilos', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdvweb.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVendaPorPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_vendido', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdvweb.produtoporpeso')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda_peso_rel', to='pdvweb.venda')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='itens_venda_peso',
            field=models.ManyToManyField(related_name='vendas_por_peso', through='pdvweb.ItemVendaPorPeso', to='pdvweb.produtoporpeso'),
        ),
    ]
