# Generated by Django 4.2.8 on 2024-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0002_venda_operador_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
