# Generated by Django 4.2.8 on 2024-01-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0003_itemvenda_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='meus_operadores',
            field=models.ManyToManyField(blank=True, related_name='meus_usuarios', to='pdvweb.operador'),
        ),
    ]
