# Generated by Django 4.2.8 on 2024-01-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0004_customuser_meus_operadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
