# Generated by Django 4.2.8 on 2024-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0004_alter_itemvendaporpeso_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='itens_venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='itens_venda_peso',
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='produtoporpeso',
            name='codigo',
            field=models.CharField(default='0', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
