# Generated by Django 4.2.8 on 2024-02-05 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0006_alter_produto_codigo_alter_produtoporpeso_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVendaPorQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='operador_responsavel',
        ),
        migrations.AlterField(
            model_name='itemvendaporpeso',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdvweb.produtoporpeso'),
        ),
        migrations.AlterField(
            model_name='itemvendaporpeso',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdvweb.venda'),
        ),
        migrations.RenameModel(
            old_name='Produto',
            new_name='ProdutoPorQuantidade',
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.AddField(
            model_name='itemvendaporquantidade',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdvweb.produtoporquantidade'),
        ),
        migrations.AddField(
            model_name='itemvendaporquantidade',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdvweb.venda'),
        ),
    ]
