# Generated by Django 4.2.8 on 2024-02-10 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0008_venda_cliente_venda_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('peso_vendido', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True)),
                ('produto_por_peso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdvweb.produtoporpeso')),
                ('produto_por_quantidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdvweb.produtoporquantidade')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdvweb.venda')),
            ],
        ),
        migrations.RemoveField(
            model_name='itemvendaporquantidade',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itemvendaporquantidade',
            name='venda',
        ),
        migrations.DeleteModel(
            name='ItemVendaPorPeso',
        ),
        migrations.DeleteModel(
            name='ItemVendaPorQuantidade',
        ),
    ]
