# Generated by Django 5.0.1 on 2024-04-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0009_itemvenda_remove_itemvendaporquantidade_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_caixa', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdvweb.operador')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdvweb.venda')),
            ],
        ),
    ]
