# Generated by Django 5.0.1 on 2024-04-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0010_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdvweb.operador'),
        ),
    ]
