# Generated by Django 5.0.1 on 2024-04-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0011_alter_caixa_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='caixasoperador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixasoperador', to='pdvweb.caixa'),
        ),
        migrations.AddField(
            model_name='venda',
            name='caixasvenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixasvenda', to='pdvweb.caixa'),
        ),
    ]
