# Generated by Django 5.0.1 on 2024-04-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvweb', '0013_alter_caixa_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdvweb.venda'),
        ),
    ]
